name: Deploy Hornet

on:
  deployment

jobs:
  deploy:
    name: Dispatch to OPS
    runs-on: ubuntu-latest
    steps:
      - name: Triggering Hornet deployment
        run: |
          curl -X POST https://api.github.com/repos/sadjy/${{ secrets.OPS_GIT_REPO }}/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.GIT_TOKEN }} \
          --data '{"event_type": "auto-${{ github.event.deployment.task }}", "client_payload": { "hornet_ref": "${{ github.event.deployment.ref }}", "environment": "${{ github.event.deployment.environment }}", "deployment_id": "${{ github.event.deployment.id }}"}}'