name: Deploy Hornet

on:
  deployment

jobs:
  deploy:
    name: Dispatch to OPS
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "${{ github.event.deployment.id }}"
        
      - name: Triggering Hornet deployment
        run: |
          curl -X POST https://api.github.com/repos/sadjy/${{ secrets.OPS_GIT_REPO }}/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.GIT_TOKEN }} \
          --data '{"event_type": "hornet-deploy", "client_payload": { "hornet_ref": "${{ github.event.payload.hornet_ref }}", "environment": "${{ github.event.hornet_ref }}", "deployment_id": "${{ github.event.deployment.ref }}"
          }}'